[profile.default]
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
    { access = "read", path = "./broadcast/SignedQuestManager.Deploy.s.sol" },
]

remappings = ["@openzeppelin/contracts=lib/openzeppelin-contracts/contracts/"]

[rpc_endpoints]
buildbear = "${BUILDBEAR_RPC}"


# [etherscan]
# buildbear = { key = "${POLYGONSCAN_API_KEY}", url = "https://api-amoy.polygonscan.com/api?" }
# base_sepolia = { key = "${BASE_BLOCKSCOUT_API_KEY}", url = "https://base-sepolia.blockscout.com/api" }
# eth_sepolia = { key = "${SEPOLIA_ETHERSCAN_API_KEY}", url = "https://api-sepolia.etherscan.io/api" }
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
